<?php
/**
 * ReplySettings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Twitter API v2
 *
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.45
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ReplySettings Class Doc Comment
 *
 * @category Class
 * @description Shows who can reply a Tweet. Fields returned are everyone, mentioned_users, and following.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReplySettings
{
    /**
     * Possible values of this enum
     */
    public const EVERYONE = 'everyone';

    public const MENTIONED_USERS = 'mentionedUsers';

    public const FOLLOWING = 'following';

    public const OTHER = 'other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EVERYONE,
            self::MENTIONED_USERS,
            self::FOLLOWING,
            self::OTHER
        ];
    }
}


